on:
  push:

jobs:
  test:
    name: Check
    strategy:
      matrix:
        go-version: [1.18.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: check out
      uses: actions/checkout@v2
    - name: install tools
      run: "go install golang.org/x/tools/cmd/goimports@latest && go install honnef.co/go/tools/cmd/staticcheck@latest && go install github.com/moznion/go-errgen/cmd/errgen@latest"
    - name: check
      run: make check
    - name: upload coverage
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

